apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmapp-frontend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "vmapp.selectorLabels" "frontend" | nindent 4 }}
spec:
  replicas: {{ .Values.replicas.frontend }}
  selector:
    matchLabels:
      {{- include "vmapp.selectorLabels" "frontend" | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "vmapp.selectorLabels" "frontend" | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccounts.frontend.name }}
      containers:
        - name: frontend
          image: "{{ .Values.image.frontendRepository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          resources:
            {{- toYaml .Values.resources.frontend | nindent 12 }}
          readinessProbe:
            httpGet: { path: /, port: 8080 }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /, port: 8080 }
            initialDelaySeconds: 15
            periodSeconds: 20
          securityContext:
            runAsNonRoot: true
            runAsUser: 101
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
            - name: cache
              mountPath: /var/cache/nginx
            - name: run
              mountPath: /var/run
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: nginx-conf
          configMap:
            name: vmapp-config
        - name: cache
          emptyDir: {}
        - name: run
          emptyDir: {}
        - name: tmp
          emptyDir: {}
