# Generated by Terraform (ansible_inventory.tf) - do not edit by hand.
# SECRET - gitignored, same as terraform.tfstate. See README's "Secrets" section.
db_password: "${db_password}"
flask_secret_key: "${flask_secret_key}"
