# Generated by Terraform (ansible_inventory.tf) - do not edit by hand.
# Non-secret app configuration, from real Terraform-managed resources.
aws_region: ${aws_region}
s3_bucket: ${s3_bucket}
sqs_queue_url: ${sqs_queue_url}
sns_topic_arn: ${sns_topic_arn}
rds_endpoint: ${rds_endpoint}
db_name: ${db_name}
db_username: ${db_username}
app_user: vmapp
app_group: vmapp
app_dir: /opt/app
