# Generated by Terraform (ansible_inventory.tf) - do not edit by hand.
# Re-run `terraform apply` to refresh this after any instance replacement.

[frontend]
vmapp-frontend ansible_host=${frontend_public_ip} ansible_user=ec2-user

[backend]
vmapp-backend ansible_host=${backend_private_ip} ansible_user=ec2-user

[worker]
vmapp-worker ansible_host=${worker_private_ip} ansible_user=ec2-user

[app:children]
backend
worker

[all:vars]
ansible_ssh_private_key_file=~/.ssh/${key_name}.pem
ansible_ssh_common_args=-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
# Left to auto-discovery (not pinned): on a fresh instance, python3.11 doesn't
# exist yet until the common role installs it, so pinning to it here would
# break the very first play. Once the common role installs python3.11 AND
# python3.11-pip (which brings setuptools/pkg_resources with it), later plays'
# auto-discovery naturally - and safely - picks up python3.11 instead of the
# older system python3.
